### ISSUE TITLE
Custom performance counters not reported

### ISSUE THREAD

**Issue by Robar666** [FrictionFree/WAD2AI#2]
In my `diagnostics.wadcfgx` I have defined some custom performance counters, which won't be reported to Application Insights.

ETW logs and the default perf counters (% Processor Time, Available Bytes) will be reported to the AI, but not the custom perf counters.

I could define the custom performance counters in `ApplicationInsights.config` like this:
```
<Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
			<Counters>
				<Add PerformanceCounter="\Process(??APP_WIN32_PROC??)\Handle Count" ReportAs="Process handle count" />
			</Counters>
</Add>
```
BUT it would be nice if there is only one place to manage those perf counters.

**Comment by FrictionFree-zz** [comment]
Assuming that your cloud service is a Worker Role then the equivalent syntax for the above perf counter collection through WAD would be:

```
<PerformanceCounters scheduledTransferPeriod="PT1M">
          <PerformanceCounterConfiguration counterSpecifier="\Process(WaWorkerHost)\Handle Count" sampleRate="PT3M" />
</PerformanceCounters>
```

Please notice that the tokenized syntax (??APP_WIN32_PROC??) won't work and you need to specify the process name. Could be (among other options) w3wp, WaWorkerHost, WaIISHost, iisexpress. Dependeing on the hosting target.

**Comment by Robar666** [comment]
Hi, thanks for the fast answer, yes I'm working with a worker role. I think my question wasn't that clear. 
I define my custom perf counters correctly in the `diagnostics.wadcfgx` (Azure Diagnostics configuration file) - they get reported to the table storage:

```
<PerformanceCounters scheduledTransferPeriod="PT30M">
          <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes" sampleRate="PT1M" />
          <PerformanceCounterConfiguration counterSpecifier="\Processor(_Total)\% Processor Time" sampleRate="PT30S" />
          <PerformanceCounterConfiguration counterSpecifier="\Process(WaWorkerHost)\% Processor Time" sampleRate="PT30S" />
          <PerformanceCounterConfiguration counterSpecifier="\Process(WaWorkerHost)\Private Bytes" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\Process(WaWorkerHost)\Thread Count" sampleRate="PT30S" />
          <PerformanceCounterConfiguration counterSpecifier="\.NET CLR LocksAndThreads(WaWorkerHost)\Total # of Contentions" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\.NET CLR Memory(WaWorkerHost)\# Bytes in all Heaps" sampleRate="PT30S" />
          <PerformanceCounterConfiguration counterSpecifier="\.NET CLR Memory(WaWorkerHost)\Gen 0 heap size" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\.NET CLR Memory(WaWorkerHost)\Gen 1 heap size" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\.NET CLR Memory(WaWorkerHost)\Gen 2 heap size" sampleRate="PT3M" />

          <!-- SignalR counters -->
          <PerformanceCounterConfiguration counterSpecifier="\SignalR(xxxserver)\Connections Connected" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\SignalR(xxxserver)\Connections Reconnected" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\SignalR(xxxserver)\Connections Current" sampleRate="PT30S" />
          <PerformanceCounterConfiguration counterSpecifier="\SignalR(xxxserver)\Connection Messages Received Total" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\SignalR(xxxserver)\Connection Messages Sent Total" sampleRate="PT3M" />
          <PerformanceCounterConfiguration counterSpecifier="\SignalR(xxxserver)\Connection Messages Received/Sec" sampleRate="PT30S" />
          <PerformanceCounterConfiguration counterSpecifier="\SignalR(xxxserver)\Connection Messages Sent/Sec" sampleRate="PT30S" />
        </PerformanceCounters>
```

_but_ they won't be reported to Application Insight.

The only custom perf counter which gets reported is the counter which is defined in the `ApplicationInsights.config` (Application Insight configuration file):

```
<Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
            <Counters>
                <Add PerformanceCounter="\Process(??APP_WIN32_PROC??)\Handle Count" ReportAs="Process handle count" />
            </Counters>
</Add>
```

_In short_
- Custom performance counters in `diagnostics.wadcfgx` won't be reported to AI.
- Custom performance counters in `ApplicationInsights.config` will be reported to AI.

If it helps there is the link to the (anonymised) `diagnostics.wadcfgx`: http://pastebin.com/V2cVwrBL
Is it a problem that the `PerformanceCollectorModule` is still active in the `ApplicationInsights.config` if the Azure Diagnostics integration is active?

**Comment by Robar666** [comment]
Okay I think I found the problem, I always checked for `performanceCounters` in AI analytics, but it seems that custom performance counters will be reported as `customMetrics`.

**Comment by FrictionFree-zz** [comment]
Thanks for sharing, we'll review the documentation to ensure this point is clear.
