### ISSUE TITLE
Script contains  hardcoded key

### ISSUE THREAD

**Issue by silverl** [FrictionFree/WAD2AI#3]
There appears to be a hardcoded instrumentation key in the VM script: ad65d3b2b50e46aba0dae7873feba7fd

**Comment by FrictionFree-zz** [comment]
It's basically used just to collect some telemetry on the usage of the script. You can safely ignore or remove it from the script before using, it will not impact the functionality.

**Comment by FrictionFree-zz** [comment]
Removed from the code just now, thanks.
